# Generated by Django 4.0.5 on 2022-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_campania', models.CharField(max_length=200)),
                ('Marca', models.CharField(max_length=200)),
                ('Canal', models.CharField(max_length=200)),
                ('Fecha_envia', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Camp', models.CharField(max_length=200)),
                ('Prioridad', models.CharField(max_length=10)),
            ],
        ),
    ]
