# Generated by Django 4.0.5 on 2022-06-28 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms_api',
            options={'ordering': ['-Created'], 'verbose_name': 'form_api', 'verbose_name_plural': 'form_apis'},
        ),
        migrations.RenameField(
            model_name='forms_api',
            old_name='Fecha_envia',
            new_name='Fecha_envio',
        ),
        migrations.RemoveField(
            model_name='forms_api',
            name='Camp',
        ),
        migrations.RemoveField(
            model_name='forms_api',
            name='Nombre_campania',
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Nombre_campanha',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre Campaña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Nombre_campo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre del Campo'),
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Table_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nombre de Tabla'),
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Tipo_usuario',
            field=models.CharField(choices=[('None', ''), ('ONLINE', 'ONLINE'), ('HARD', 'HARD'), ('SOFT', 'SOFT'), ('TODOS', 'TODOS'), ('ACABADOS', 'ACABADOS')], default=None, max_length=10, verbose_name='Tipo de usuario'),
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de edición'),
        ),
        migrations.AddField(
            model_name='forms_api',
            name='Valor_Campo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Valor del Campo'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Canal',
            field=models.CharField(choices=[('', ''), ('EMAIL', 'Email'), ('CELULAR', 'Celular')], max_length=10, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Marca',
            field=models.CharField(choices=[('', ''), ('HC', 'Homecenter'), ('CT', 'Constructor')], max_length=10, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Prioridad',
            field=models.CharField(max_length=10, verbose_name='Prioridad'),
        ),
    ]
