# Generated by Django 4.0.5 on 2022-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_forms_api_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_api',
            name='Canal',
            field=models.CharField(choices=[('', ''), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Tipo_usuario',
            field=models.CharField(choices=[('None', ''), ('ONLINE', 'ONLINE'), ('HARD', 'HARD'), ('SOFT', 'SOFT'), ('TODOS', 'TODOS'), ('ACABADOS', 'ACABADOS'), ('MIX', 'MIX')], default=None, max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
