# Generated by Django 4.0.4 on 2023-01-27 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_forms_api_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms_api',
            name='Categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Canal',
            field=models.CharField(choices=[('', ''), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Tipo_usuario',
            field=models.CharField(choices=[('None', ''), ('ONLINE', 'ONLINE'), ('HARD', 'HARD'), ('SOFT', 'SOFT'), ('TODOS', 'TODOS'), ('ACABADOS', 'ACABADOS'), ('MIX', 'MIX')], default=None, max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
