# Generated by Django 4.0.5 on 2022-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_alter_forms_api_canal_alter_forms_api_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=200, verbose_name='Nombre')),
                ('select', models.CharField(choices=[('', ''), ('S1', 'Seleccion 1'), ('S2', 'Seleccion 2'), ('S3', 'Seleccion 3'), ('S4', 'Seleccion 4'), ('S5', 'Seleccion 5')], max_length=10, verbose_name='Desplegables')),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Query',
                'ordering': ['-created'],
            },
        ),
    ]
