# Generated by Django 4.0.5 on 2022-10-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_api',
            name='Nombre_campo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ciclo de Vida'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Table_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Segmento Valor'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Tipo_usuario',
            field=models.CharField(choices=[('None', ''), ('ONLINE', 'ONLINE'), ('HARD', 'HARD'), ('SOFT', 'SOFT'), ('TODOS', 'TODOS'), ('ACABADOS', 'ACABADOS'), ('MIX', 'MIX')], default=None, max_length=10, verbose_name='Segmento Necesidad'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Valor_Campo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tienda Frecuente'),
        ),
    ]
