# Generated by Django 4.0.5 on 2022-10-21 20:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_alter_forms_api_segmento_necesidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_api',
            name='Ciclo_vida',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('DESARROLLO', 'DESARROLLO'), ('MADURO', 'MADURO'), ('VENTA EMPRESA', 'VENTA EMPRESA'), ('POTENCIAL', 'POTENCIAL'), ('REACTIVADO', 'REACTIVADO'), ('FUGADO', 'FUGADO'), ('ADQUISICION', 'ADQUISICION'), ('VENTA', 'VENTA'), ('RETENCION', 'RETENCION'), ('NUEVO', 'NUEVO'), ('RECUPERACION', 'RECUPERACION')], max_length=107, verbose_name='Ciclo de Vida'),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Segmento_valor',
            field=models.CharField(choices=[('', ''), ('S', 'S'), ('REGULAR', 'REGULAR'), ('VENTA EMPRESA', 'VENTA EMPRESA')], max_length=20, verbose_name='Segmento Valor'),
        ),
    ]
