# Generated by Django 4.0.5 on 2022-10-21 20:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_alter_forms_api_ciclo_vida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_api',
            name='Ciclo_vida',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('DESARROLLO', 'DESARROLLO'), ('MADURO', 'MADURO'), ('VENTA EMPRESA', 'VENTA EMPRESA'), ('POTENCIAL', 'POTENCIAL'), ('REACTIVADO', 'REACTIVADO'), ('FUGADO', 'FUGADO'), ('ADQUISICION', 'ADQUISICION'), ('VENTA', 'VENTA'), ('RETENCION', 'RETENCION'), ('NUEVO', 'NUEVO'), ('RECUPERACION', 'RECUPERACION')], max_length=107),
        ),
        migrations.AlterField(
            model_name='forms_api',
            name='Segmento_necesidad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('CONSTRUCTOR DE JARDINES', 'CONSTRUCTOR DE JARDINES'), ('TBD', 'TBD'), ('VENTA EMPRESA', 'VENTA EMPRESA'), ('TODERO', 'TODERO'), ('PINTOR', 'PINTOR'), ('ELECTRICISTA', 'ELECTRICISTA'), ('ORNAMENTADOR', 'ORNAMENTADOR'), ('MULTIESPECIALIDAD CONTRATISTA', 'MULTIESPECIALIDAD CONTRATISTA'), ('HOGAR', 'HOGAR'), ('MAESTRO', 'MAESTRO'), ('ESPECIALISTA ACABADOS', 'ESPECIALISTA ACABADOS'), ('CARPINTERO', 'CARPINTERO'), ('PLOMERO', 'PLOMERO'), ('NO CONTRUCTOR', 'NO CONTRUCTOR'), ('DECORADOR', 'DECORADOR'), ('ESPECIALISTA DRYWALL', 'ESPECIALISTA DRYWALL')], max_length=212),
        ),
    ]
