# Generated by Django 4.0.5 on 2022-10-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_alter_forms_api_ciclo_vida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms_api',
            name='Ciclo_vida',
        ),
        migrations.RemoveField(
            model_name='forms_api',
            name='Segmento_valor',
        ),
        migrations.RemoveField(
            model_name='forms_api',
            name='Tienda_frecuente',
        ),
    ]
