# Generated by Django 4.0.5 on 2022-10-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_remove_forms_api_segmento_necesidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms_api',
            name='Segmento_valor',
        ),
    ]
