# Generated by Django 4.0.5 on 2022-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0015_alter_forms_api_ciclo_vida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_api',
            name='Tipo_usuario',
            field=models.CharField(blank=True, choices=[('', ''), ('ONLINE', 'ONLINE'), ('HARD', 'HARD'), ('SOFT', 'SOFT'), ('TODOS', 'TODOS'), ('ACABADOS', 'ACABADOS'), ('MIX', 'MIX')], default=None, max_length=10, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
