# Generated by Django 4.0.5 on 2022-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='N_registro',
            field=models.IntegerField(verbose_name='Numero de registro'),
        ),
    ]
