# Generated by Django 4.0.5 on 2022-06-22 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0002_alter_camp_n_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'ordering': ['-Created'], 'verbose_name': 'Camp', 'verbose_name_plural': 'Camps'},
        ),
        migrations.AddField(
            model_name='camp',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='Updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de edición'),
        ),
    ]
